INSERT INTO users (username, password, full_name, email, gender) VALUES
('Kobby', '$argon2id$v=19$m=65536,t=3,p=4$l079JRQ4ZC565vPJp727TIUfqls2EcCNAE4zSpYn0q4$ATE6KWSwP0cH889OKqdk9KnG87NF7c6CiyX4XNLjdz4', 'Kwabena Edusei', 'kobby@gmail.com', 'M'),
('Ama', '$argon2id$v=19$m=65536,t=3,p=4$cb9LqPfDVp4UWq16sxi9pKaYBs62qZLYbmEN4wTU9GA$knUuUmlohiQVxdN08spX8+yETI4QzaPRNBjfquhmMmg', 'Ama Asante', 'ama@gmail.com', 'F'),
('Kwame', '$argon2id$v=19$m=65536,t=3,p=4$l079JRQ4ZC565vPJp727TIUfqls2EcCNAE4zSpYn0q4$ATE6KWSwP0cH889OKqdk9KnG87NF7c6CiyX4XNLjdz4', 'Kwame Nkrumah', 'kwame@example.com', 'M'),
('Efia', '$argon2id$v=19$m=65536,t=3,p=4$cb9LqPfDVp4UWq16sxi9pKaYBs62qZLYbmEN4wTU9GA$knUuUmlohiQVxdN08spX8+yETI4QzaPRNBjfquhmMmg', 'Efia Darko', 'efia@example.com', 'F'),
('Kofi', '$argon2id$v=19$m=65536,t=3,p=4$l079JRQ4ZC565vPJp727TIUfqls2EcCNAE4zSpYn0q4$ATE6KWSwP0cH889OKqdk9KnG87NF7c6CiyX4XNLjdz4', 'Kofi Mensah', 'kofi@example.com', 'M'),
('Adwoa', '$argon2id$v=19$m=65536,t=3,p=4$cb9LqPfDVp4UWq16sxi9pKaYBs62qZLYbmEN4wTU9GA$knUuUmlohiQVxdN08spX8+yETI4QzaPRNBjfquhmMmg', 'Adwoa Boateng', 'adwoa@example.com', 'F'),
('Yaw', '$argon2id$v=19$m=65536,t=3,p=4$l079JRQ4ZC565vPJp727TIUfqls2EcCNAE4zSpYn0q4$ATE6KWSwP0cH889OKqdk9KnG87NF7c6CiyX4XNLjdz4', 'Yaw Osei', 'yaw@example.com', 'M')
ON CONFLICT DO NOTHING;

INSERT INTO posts (user_id, title, body, is_draft) VALUES
(1, 'The 5-Minute Rule That Actually Works', 'We''ve all been there: a daunting list of small tasks that we keep rescheduling. "Reply to that email," "Clear the kitchen counter," "File that document." They linger, causing low-grade stress. Enter the 5-minute rule. It''s simple: if a task will take less than five minutes, do it immediately. Don''t write it down. Don''t mentally schedule it for later. Just do it now. The magic isn''t just in completing tiny tasks. It''s in the momentum. Crossing off three quick things in 15 minutes can fuel the motivation to tackle a bigger project. It clears mental clutter, making space for focused work. Try it for a day. You might be shocked by how light your to-do list feels by sunset.', false),
(2, 'My Go-To "Empty Fridge" Pasta', 'You stare into the fridge. There''s a half-used onion, a wilting bunch of herbs, a lemon, and the eternal block of parmesan. It''s not a crisis it''s an opportunity for aglio e olio. This classic Roman pasta needs only pantry staples: garlic, red pepper flakes, olive oil, and spaghetti. It''s a lesson in simplicity. The key is to infuse the oil slowly over low heat, toasting the garlic and chili without burning. Reserve a cup of the starchy pasta water before draining this, along with a vigorous stir, creates the silky, emulsified sauce. Toss in your sad herbs for freshness and a squeeze of that lemon for brightness. Finish with a mountain of grated parmesan. Dinner is served, from "nothing" to something sublime.', false),
(1, 'Is AI Your Co-pilot or Your Autopilot?', 'AI tools are everywhere now, promising to write our emails, generate our reports, and even craft our ideas. It''s tempting to switch to autopilot and let the tool do the work. But the real power lies in treating AI as a co-pilot. You still hold the controls. You provide the direction, the critical thinking, and the final judgment. Use AI to brainstorm first drafts, overcome writer''s block, or summarize complex information. Then, take the output and make it yours edit, refine, and add your unique voice and insight. The tool handles the heavy lifting; you steer toward the destination. Don''t just accept what it gives you. Challenge it, guide it, and collaborate with it. That''s where the magic happens.', false),
(2, 'The Joy of a Screen-Free Hour', 'I challenged myself to one hour with no screens: no phone, no laptop, no TV. The first ten minutes were filled with phantom buzzes and a nagging sense of "I should be checking something." Then, something shifted. I picked up a novel I''d been meaning to finish. I made a detailed grocery list on actual paper. I just sat with a cup of tea and watched the birds in the garden. The constant, low hum of digital anxiety faded. It wasn''t revolutionary, but it was restorative. In that quiet space, my thoughts felt less scattered. My focus deepened. I''m not swearing off technology, but I am carving out a little more of that analog space each day. Try it. Your notifications will wait.', false),
(1, 'Found: The Perfect Bench', 'Every neighborhood has one a spot that feels uniquely yours. I found mine on a forgotten side path in the local park. It''s a simple green wooden bench, slightly weathered, facing a small, burbling creek that most people miss. On my lunch break, I''ll sit there for just fifteen minutes. No agenda. I watch the water ripple over stones, listen to the leaves rustle, and feel the sun through the branches. It''s a daily reset button. We chase grand adventures, but sometimes peace is hidden in plain sight. I urge you to find your bench, your corner, your quiet stretch of path. Claim it. Visit it often. These small anchors make a city feel like home.', false),
(3, 'Building a Morning Routine That Sticks', 'The key to a successful morning routine isn''t complexity—it''s consistency. Start with just two non-negotiables: hydration and movement. Drink a glass of water before checking your phone, and do five minutes of stretching or walking. These tiny anchors create a foundation that naturally expands over time. Within weeks, you''ll find yourself adding journaling, meditation, or planning without feeling overwhelmed.', false),
(4, 'How I Learned to Stop Scrolling and Start Living', 'I deleted all social media apps for 30 days. The first week was withdrawal—boredom, FOMO, phantom vibrations. By week two, my mind felt quieter. I started reading again, calling friends instead of liking their posts, and noticing details in my neighborhood I''d missed for years. I didn''t quit social media forever, but now I use it intentionally—not compulsively.', false),
(5, 'The Power of "No" in a World of Yes', 'Saying ''no'' used to make me anxious. I feared missing opportunities or disappointing people. But I''ve learned that every ''yes'' to something unimportant is a ''no'' to what truly matters—my time, energy, and peace. Now, I pause before answering requests. If it doesn''t align with my priorities, I decline gracefully. My relationships have deepened, not suffered.', false),
(6, 'My Grandmother''s Plantain Recipe', 'Peel ripe plantains and slice them diagonally. Fry in coconut oil until golden on both sides. Sprinkle with sea salt and a dash of cinnamon while hot. Serve with a dollop of Greek yogurt. This simple dish connects me to childhood Sundays at my grandmother''s kitchen in Kumasi. Food is memory, and this recipe is love on a plate.', false),
(7, 'Why Walking Is the Ultimate Productivity Hack', 'Forget expensive standing desks or productivity apps. The most effective tool I''ve found is a 20-minute walk—no podcast, no music, just moving. Ideas flow, problems untangle, and stress dissolves. Neuroscience shows rhythmic movement boosts creative thinking. Try it after lunch or when stuck on a problem. Your brain will thank you.', false),
(3, 'Embracing the Messy Middle of Creative Work', 'We celebrate finished projects but rarely talk about the messy middle—the phase where everything feels wrong, unclear, and frustrating. That''s where growth happens. Instead of quitting, I''ve learned to lean into the discomfort. I set a timer for 25 minutes and commit to working through the fog. Almost always, clarity emerges on the other side.', false),
(4, 'Digital Minimalism: Less Tech, More Life', 'I unsubscribed from 50 newsletters, turned off all non-essential notifications, and moved apps off my home screen. The result? Two extra hours of focused time each day. Digital minimalism isn''t about rejecting technology—it''s about reclaiming attention. Ask yourself: does this tool serve my values, or distract from them?', false),
(5, 'The Art of Asking for Help', 'Asking for help used to feel like weakness. Now I see it as collaboration. Last week, I struggled with a coding problem for hours. Finally, I messaged a colleague. In 10 minutes, we solved it together—and I learned a new approach. Vulnerability builds trust. Don''t let pride steal your progress.', false),
(6, 'Rainy Day Comfort: My Go-To Soup', 'Chop onions, carrots, and celery. Sauté in olive oil until soft. Add diced tomatoes, vegetable broth, and a can of white beans. Simmer for 20 minutes. Finish with chopped kale and a squeeze of lemon. This soup costs less than $5, feeds four, and tastes like a hug. Perfect for gray afternoons when you need warmth from the inside out.', false),
(7, 'Finding Focus in a Distracted World', 'Deep work is a superpower. To cultivate it, I block 90-minute focus sessions in my calendar. During these, my phone is in another room, email is closed, and I work on one meaningful task. It''s not easy—but the output in those 90 minutes often exceeds a full day of fragmented work. Protect your attention fiercely; it''s your most valuable resource.', false)
ON CONFLICT DO NOTHING;

INSERT INTO comments (id, user_id, post_id, body, created_at) VALUES
(1, 1, 1, 'Great tip! I''ve been using this for a week and it really helps.', '2026-01-25 14:30:00'),
(2, 2, 1, 'Does this work for bigger tasks too?', '2026-01-26 09:15:00'),
(3, 1, 2, 'Love this recipe! Added some mushrooms and it turned out amazing.', '2026-01-27 18:45:00'),
(4, 2, 3, 'Interesting perspective on AI collaboration.', '2026-01-28 11:20:00'),
(5, 2, 4, 'I need to try this digital detox!', '2026-01-29 16:10:00'),
(6, 1, 5, 'Found my own bench yesterday. Thanks for the inspiration!', '2026-01-30 08:55:00'),
(7, 1, 6, 'This resonates so much! I''ve been trying to build a consistent morning routine too.', '2026-01-31 07:40:00'),
(8, 2, 6, 'Do you use a journal? What kind?', '2026-02-01 13:25:00'),
(9, 3, 7, 'I did a similar social media detox last year. Life-changing!', '2026-02-02 19:50:00'),
(10, 4, 8, 'So true about saying no. It''s liberating once you get past the guilt.', '2026-02-03 10:05:00'),
(11, 5, 9, 'Your plantain recipe sounds delicious! Do you use overripe plantains?', '2026-02-04 15:30:00'),
(12, 6, 10, 'I walk daily now—best decision ever for mental clarity.', '2026-02-05 12:15:00'),
(13, 7, 11, 'The "messy middle" is real. Thanks for naming it!', '2026-02-06 17:40:00'),
(14, 1, 12, 'Digital minimalism changed my life too. Started with turning off notifications.', '2026-02-07 09:20:00'),
(15, 2, 13, 'Asking for help is hard but so necessary. Great reminder!', '2026-02-08 14:55:00'),
(16, 3, 14, 'Made your soup last night—perfect for the rainy weather!', '2026-02-09 20:10:00'),
(17, 4, 15, 'I struggle with deep work. Any tips for avoiding the urge to check email?', '2026-02-10 06:30:00'),
(18, 5, 2, 'Tried your pasta recipe—added mushrooms like you suggested. Amazing!', '2026-02-10 07:00:00'),
(19, 6, 4, 'Did your screen-free hour become a daily habit?', '2026-02-10 07:05:00'),
(20, 7, 1, 'The 5-minute rule saved my productivity this week. Thank you!', '2026-02-10 07:08:00')
ON CONFLICT DO NOTHING;
